name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_OUTPUT

      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Install Android SDK 34
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: false

      - name: Update Gradle Wrapper
        working-directory: ./project
        run: |
          sed -i "s/distributionUrl=.*/distributionUrl=https\\:\/\/services.gradle.org\/distributions\/gradle-8.2-all.zip/g" gradle/wrapper/gradle-wrapper.properties
          cat gradle/wrapper/gradle-wrapper.properties | grep distributionUrl

      - name: Update AGP Version
        working-directory: ./project
        run: |
          sed -i -E "s/(com\.android\.tools\.build:gradle:)[^'\"]+/\18.2.0/g" build.gradle
          grep 'com.android.tools.build:gradle' build.gradle

      - name: Clean Project
        working-directory: ./project
        run: ./gradlew clean

      - name: Build the App
        working-directory: ./project
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: ./project/app/build/outputs/apk/**/*.apk
