name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_OUTPUT

      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Install Android SDK 34
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: false

      - name: Build the app
        working-directory: ./project
        run: |
          # 1. 修复 AGP 版本替换
          sed -i -E "s/(com\.android\.tools\.build:gradle:)[^'\"]+/\18.2.0/g" build.gradle

          # 2. 动态添加仓库
          sed -i "/repositories {/a \        google()" build.gradle
          sed -i "/repositories {/a \        mavenCentral()" build.gradle

          # 3. 强制统一 AGP 版本
          echo -e "\nallprojects {\n  configurations.all {\n    resolutionStrategy.force 'com.android.tools.build:gradle:8.2.0'\n  }\n}" >> build.gradle

          # 4. 验证配置
          echo "=== AGP 版本检查 ==="
          grep 'com.android.tools.build:gradle' build.gradle
          echo "=== 仓库配置检查 ==="
          grep 'repositories' build.gradle

          # 5. 执行构建
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: ./project/app/build/outputs/apk/**/*.apk
