name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_OUTPUT

      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Install Android SDK 34
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: false

      - name: Build the app
        working-directory: ./project
        run: |
          # 修复 1：预生成 gradlew 并赋予权限
          touch gradlew && chmod +x gradlew

          # 修复 2：升级 Gradle 到 8.2
          ./gradlew wrapper --gradle-version 8.2 --distribution-type bin

          # 修复 3：精确替换 AGP 版本（兼容单/双引号）
          sed -i "s/com\.android\.tools\.build:gradle:[^'\"']*/com.android.tools.build:gradle:8.2.0\"/g" build.gradle

          # 修复 4：强制添加 Google 仓库配置
          sed -i "/repositories {/a \        google()" build.gradle
          sed -i "/repositories {/a \        mavenCentral()" build.gradle

          # 修复 5：注入依赖统一策略（处理第三方插件冲突）
          echo -e "\nallprojects {\n  configurations.all {\n    resolutionStrategy.force 'com.android.tools.build:gradle:8.2.0'\n  }\n}" >> build.gradle

          # 调试：验证关键配置
          echo "=== AGP 版本 ==="
          grep 'com.android.tools.build:gradle' build.gradle
          echo "=== 仓库配置 ==="
          grep 'repositories' build.gradle
          echo "=== 依赖强制策略 ==="
          tail -n 5 build.gradle

          # 修复 6：优化内存配置
          echo "org.gradle.jvmargs=-Xmx2048m" >> gradle.properties

          # 执行构建
          ./gradlew assembleDebug --stacktrace --scan

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: ./project/app/build/outputs/apk/**/*.apk
