name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_OUTPUT

      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Install Android SDK 34
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: false

      - name: Build the app
        working-directory: ./project
        run: |
          touch gradlew && chmod +x gradlew  # [1](@ref)
          ./gradlew wrapper --gradle-version 8.2 --distribution-type bin
          sed -i "s/com\.android\.tools\.build:gradle:.*/com.android.tools.build:gradle:8.2.0\"/g" build.gradle  # [2](@ref)
          chmod +x gradlew
          ls -l gradlew && grep 'gradle' build.gradle
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: ./project/app/build/outputs/apk/**/*.apk
