name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_OUTPUT

      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Install Android SDK 34
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: false

      - name: Build the app
        working-directory: ./project
        run: |
          # 1. 确保 gradlew 可执行
          touch gradlew && chmod +x gradlew

          # 2. 强制升级 Gradle 到 8.2
          ./gradlew wrapper --gradle-version 8.2 --distribution-type bin

          # 3. 修复 AGP 版本替换（兼容单/双引号）
          sed -i -E "s/(com\.android\.tools\.build:gradle:)[^'\"]+/\18.2.0\"/g" build.gradle

          # 4. 动态添加 Google 和 Maven 仓库
          sed -i "/repositories {/a \        google()" build.gradle
          sed -i "/repositories {/a \        mavenCentral()" build.gradle

          # 5. 强制统一所有依赖的 AGP 版本（解决第三方插件冲突）
          echo -e "\nallprojects {\n  configurations.all {\n    resolutionStrategy.force 'com.android.tools.build:gradle:8.2.0'\n  }\n}" >> build.gradle

          # 6. 优化内存配置
          echo "org.gradle.jvmargs=-Xmx2048m" >> gradle.properties

          # 7. 调试：验证关键配置
          echo "=== AGP 版本检查 ==="
          grep 'com.android.tools.build:gradle' build.gradle
          echo "=== 仓库配置检查 ==="
          grep 'repositories' build.gradle
          echo "=== 依赖强制策略 ==="
          tail -n 6 build.gradle

          # 8. 执行构建
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: ./project/app/build/outputs/apk/**/*.apk
